In [1]:
import numpy as np
import matplotlib.pyplot as plt

import hphc2

C = 299792458.
G = 6.67408*1e-11
Mo = 1.989*1e30
Mpc = 3.086*1e22

In [2]:
arg_plus = {'iota_':np.pi/3, 'beta_':np.pi/3, 'D_':100. , 'm1_':10., 'm2_':10., 'f_':30., 'f0_':10., 'Fp_':1.0, 'Fc_':0.0, 'et0_':0.1, 'phic_':0., 'tc_':0.}
fplus = hphc2.Fn(**arg_plus)

In [3]:
fplus.psi_l(0)

array([27.27201545362122, -24.87383906306776, -261.3707465317626,
       -766.03128047099, -1612.1164425229026, -2866.259412844815,
       -4590.370482970628, -6842.748507467817, -9678.801511791158,
       -13151.547685325884], dtype=object)

In [4]:
fplus.psi_l(0)

array([    21.31066661,    -32.23955683,   -269.61204315,   -774.8677692 ,
        -1621.36964844,  -2875.80395822,  -4600.1126461 ,  -6852.61516064,
        -9688.73377332, -13161.49698888])

In [8]:
type(fplus.k_())

numpy.ndarray

In [6]:
1+ \
\
2

3

In [5]:
np.log10(10)

1.0

In [6]:
tt = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt/100000000000000000000

array([1e-20, 2.097152e-14, 1.0460353203e-10, 4.398046511104e-08,
       4.76837158203125e-06, 0.00021936950640377855, 0.00558545864083284,
       -0.09223372036854775, -0.012614753107449505, 0.038758200196842126],
      dtype=object)

In [26]:
np.array([10000000000000000000000])/1

array([1e+22], dtype=object)