In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import hphc15
import hphc16
import hphc14

import h0CpxSpx5
import h05CpxSpx5
import h1CpxSpx5
import time

C = 299792458.
G = 6.67408*1e-11
Mo = 1.989*1e30
Mpc = 3.086*1e22

In [11]:
mass_1 = 23.5
mass_2 = 21.5
symmetric_mass_ratio = (mass_1*mass_2)/((mass_1+mass_2)**2)
maximum_f = (C**3)/( G*(mass_1+mass_2)*Mo*np.pi*6**(3/2) )
mass_diff = (mass_1-mass_2)*Mo

In [12]:
farray=np.array([20,30,40])
index = np.array(np.where( (farray >= 20) & (farray <= 80) )).flatten()

In [15]:
index[0]

0

In [2]:
#m1=23.5, m2=21.5
injection_parameters = dict(chirp_mass=19.564163812778446, mass_ratio=0.9148936170212766, \
                            eccentricity=0.1, luminosity_distance=200.0, theta_jn=0.4, \
                            psi=0.1, phase=1.2, geocent_time=1180002601.0, ra=45.0, dec=5.73)

In [2]:
arg_plus = {'iota_':0.4, 'beta_':0.1, 'D_':200.0 , 'm1_':23.5, 'm2_':21.5, 'f_':50., 'f0_':20.0, 'Fp_':1.0, 'Fc_':0.0, 'et0_':0.1, 'phic_':1.2, 'tc_':1180002601.0}
arg_plus2 = {'iota_':0.4, 'beta_':0.1, 'D_':200.0*Mpc , 'm1_':23.5, 'm2_':21.5, 'f_':50., 'f0_':20.0, 'et0_':0.1, 'phic_':1.2, 'tc_':1180002601.0}
arg_plus3 = {'iota_':0.4, 'beta_':0.1, 'D_':200.0*Mpc , \
                        'f_':50.0, 'f0_':20.0, 'et0_':0.1, 'phic_':1.2, \
                        'tc_':1180002601.0, 'M_':45.0*Mo, 'eta_':0.24950617283950619, \
                        'ff_':97.68922304308887, 'delta_':3.9780000000000004e+30}
arg_plus4 = {'iota_':0.4, 'beta_':0.1, 'D_':200.0*Mpc , \
                        'farray_':np.array([20,30,40]), 'f0_':20.0, 'et0_':0.1, 'phic_':1.2, \
                        'tc_':1180002601.0, 'M_':45.0*Mo, 'eta_':0.24950617283950619, \
                        'ff_':97.68922304308887, 'delta_':3.9780000000000004e+30}
#fplus = hphc5.Fn(**arg_plus)
#fplus2 = hphc11.Fn(**arg_plus3)

fplus14 = hphc14.Fn(**arg_plus4)
fplus15 = hphc15.Fn(**arg_plus4)
fplus16 = hphc16.Fn(**arg_plus4)

In [3]:
fplus14.htilde()

(array([-4.15672870e-23+1.12145642e-22j, -5.36029112e-23+3.18179166e-23j,
        -3.64941971e-23+2.33325147e-23j]),
 array([-1.12019602e-22-4.15464626e-23j, -3.17752409e-23-5.34641083e-23j,
        -2.32564747e-23-3.63700052e-23j]))

In [4]:
9+-3

6

In [3]:
fplus3.htilde()

array([[0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [1., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [8]:
for ii in range(10):
    print(fplus2.htilde()[2](ii,-2))

(1.3444100658748108+0.2725254121916997j)
(8.001496166323534+1.62198357199795j)
(-0.910603342507551-0.1845884358940215j)
(-0.2641123967729858-0.053538233328132546j)
(-0.04094592084499716-0.008300149068424667j)
(-0.005242189582493422-0.0010626444364104347j)
(-0.0006207929760552522-0.00012584096621969464j)
(-6.845888126617825e-05-1.3877302252350987e-05j)
0j
0j


In [9]:
for ii in range(10):
    print(fplus3.htilde()[2](ii,-2))

(1.3444100658748106+0.2725254121916996j)
(8.001496166323534+1.62198357199795j)
(-0.910603342507551-0.1845884358940215j)
(-0.2641123967729858-0.053538233328132546j)
(-0.040945920844997145-0.008300149068424663j)
(-0.005242189582493417-0.0010626444364104336j)
(-0.0006207929760552516-0.00012584096621969453j)
(-6.845888126617825e-05-1.3877302252350987e-05j)
0j
0j


In [10]:
for ii in range(10):
    print(fplus.xi_l1(ii+1,-2))

(1.030381442126504+1.0609204612826066j)
(6.056735345095147+6.236248241159705j)
(-0.7081009087760657-0.7290879979582396j)
(-0.20360106184906185-0.20963550353618993j)
(-0.03151192205976186-0.03244588995949675j)
(-0.004031715450029151-0.004151209678405673j)
(-0.0004772863552720532-0.0004914324341421442j)
(-5.2624676220296714e-05-5.418439568870892e-05j)
0j
0j


In [5]:
fplus.eccn(1,-2)

0.06003624127684828

In [8]:
for ii in range(10): 
    test44 = h1CpxSpx5.Fn(fplus.eccn(ii+1,-2),0.1,0.4,0.24950617283950619)
    print(test44.cplus(ii+1,-2))

1.3603317094397676
8.101835418925221
-0.9224395688690399
-0.26761784306624226
-0.041496643466270265
-0.005313342463932207
-0.000629275046849544
-6.93989644152383e-05
0.0
0.0


In [3]:
t0 = time.time()
zz = fplus14.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.4452


In [4]:
t0 = time.time()
zz = fplus15.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.5072


In [5]:
t0 = time.time()
zz = fplus16.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.4882


In [9]:
t0 = time.time()
for ii in range(100):
    zz = fplus3.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 1.1194


In [8]:
t0 = time.time()
for ii in range(100):
    zz = fplus2.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.8051


In [13]:
fplus1.eccn(1,-2)

NameError: name 'fplus1' is not defined

In [5]:
fplus2.xi_l0(1,-2)

(-0.05800799034431211+0.1004727865213135j)

In [12]:
(1-766.4737128241678**2)**(7/4)

(8815036911.772095-8815036911.772099j)

In [14]:
np.power( ((1-766.4737128241678**2)*1j),(7/4) )/(1j)**(7/4)

(8815036911.772104+8815036911.772108j)

In [6]:
np.power((1-0.4**2),7/4,dtype=np.complex)

(0.7370360838796302+0j)

In [5]:
(1-766.4737128241678**2)**(7/4)

(8815036911.772095-8815036911.772099j)

In [7]:
fplus.htilde()

(5.5342731782875834e-24-5.013560269811376e-25j)

In [9]:
for ii in range(10):
    xil = fplus2.psi_l(ii+1,-3)
    print(xil)

-174.2305008050212
-141.35520752921354
-136.0392938134141
-157.71391805383195
-213.6917374899976
-312.35550884416284
-461.9902029791834
-670.5616693215887
-945.6972131545898
-1294.712198305867


In [33]:
for ii in range(10):
    et = fplus2.eccn(ii+1,-3)
    fn = h05CpxSpx5.Fn(et,sp.pi/3,sp.pi/3)
    Cp0 = fn.splus(ii+1,-3)
    print(Cp0, '  ',et)

0.0    0.014639220994070659
0.0    0.015169740956777217
0.0    0.015857117600498096
0.0    0.01636531750028254
0.0    0.016727243794910494
0.0    0.01699176458286298
0.0    0.017191620454341295
0.0    0.017347252350343536
0.0    0.01747160429999319
0.0    0.017573132516361795


In [32]:
ee = 0.01636531750028254
iota = np.pi/3
beta = np.pi/3
ee**3*( - 38*np.sin(iota)*np.sin(3*beta) - 38*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**(8*np.sin(iota)*np.sin(3*beta) + 8*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**5*(176/3*np.sin(iota)*np.sin(3*beta) + 176/3*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))

0.9999999999999957

In [34]:
ee = 0.01636531750028254
iota = np.pi/3
beta = np.pi/3
ee**3*( - 38*np.sin(iota)*np.sin(3*beta) - 38*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee*(8*np.sin(iota)*np.sin(3*beta) + 8*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**5*(176/3*np.sin(iota)*np.sin(3*beta) + 176/3*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))

1.7334579170191625e-17

In [4]:
import time
t0 = time.time()
fplus.htilde()
#fplus2.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0406


In [5]:
import time
t0 = time.time()
print(fplus.htilde())
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

(-9.563236707058214e-24+7.965974785544314e-26j)
Execution took 5.4276


In [7]:
import time
t0 = time.time()
et = fplus.eccn(1,2)
fn = h05CpxSpx4.Fn(et,sp.pi/3,sp.pi/3)
fn.cplus(1,2)
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0179


In [16]:
for i in range(10):
    j=i+1
    et = fplus.eccn(j,2)
    fn = h1CpxSpx4.Fn(et,sp.pi/3,sp.pi/3,0.25)
    print(fn.scross(j,2),',',et)

2.430113800922941e-07 , 0.0055170314788476876
1.5546428121964128e-08 , 0.010164039876179361
1.0488859715430617e-09 , 0.01441331376393247
3.0807129028019986e-11 , 0.01572215720769032
0.0 , 0.016379140319968857
0.0 , 0.016779961721317377
0.0 , 0.017052124477030414
0.0 , 0.01724994913866151
0.0 , 0.01740070874052484
0.0 , 0.01751967950472511


In [9]:
mm=np.array([1,2,3])

In [12]:
float(1j+1)

TypeError: can't convert complex to float

In [15]:
import time
t0 = time.time()
fplus.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 5.1655


In [27]:
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])
y = np.array([1, 1, 1, 1, 1])

In [28]:
mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
my = ma.masked_array(y, mask=[0, 0, 0, 1, 0])

In [32]:
z = np.array([mx,my])

In [34]:
mz = ma.masked_array(z, mask=[[0, 0, 0, 1, 0],[0, 0, 0, 1, 0]])

In [35]:
mz

masked_array(
  data=[[1, 2, 3, --, 5],
        [1, 1, 1, --, 1]],
  mask=[[False, False, False,  True, False],
        [False, False, False,  True, False]],
  fill_value=999999)

In [13]:
np.array([1.0,2.0,False,4.0])/np.array([1.0,1.0,False,1.0])

/home/hemantakumar.phurailatpam/anaconda3/envs/bilby/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 1.,  2., nan,  4.])

In [5]:
for (ii,jj) in np.array([(1,2),(2,3)]):
    print(ii)
    print(jj)

1
2
2
3


In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [15]:
class test1:
    def __init__(self, xx_, yy_):
        self.xx_ = xx_
        self.yy_ = yy_
        
    def k1_(self):
        k2 = self.k2_
        xx = self.xx_
        yy = self.yy_
        
        global zz
        zz = 3
        
        z = k2(xx,yy)
        
        return(z)
    
    def k2_(self, a_, b_):
        
        k3 = a_ + b_ + zz
        
        return(k3)
        

In [7]:
test2 = np.array([1,2,3,0,5,0])
test3 = np.array([1,1,1,4,1,6])

In [12]:
test3[test2!=0 or test2==1] = test2[test2!=0]**2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
test3

array([ 1,  4,  9,  4, 25,  6])

In [9]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [8]:
arr = np.linspace(0,100,10)
np.where((arr>20) & (arr<100))

(array([2, 3, 4, 5, 6, 7, 8]),)