In [1]:
import numpy as np
import matplotlib.pyplot as plt

import hphc2

C = 299792458.
G = 6.67408*1e-11
Mo = 1.989*1e30
Mpc = 3.086*1e22

In [2]:
arg_plus = {'iota_':np.pi/3, 'beta_':np.pi/3, 'D_':10. , 'm1_':10., 'm2_':10., 'f_':100., 'f0_':20., 'Fp_':1.0, 'Fc_':0.0, 'et0_':0.1, 'phic_':0., 'tc_':0.}
fplus = hphc2.Fn(**arg_plus)

In [3]:
fplus.k_()

array([0.89915198, 0.44553458, 0.30807497, 0.24058714, 0.19996779,
       0.17258576, 0.15274385, 0.13762746, 0.12568038, 0.11596934])

In [4]:
fplus.psi_l(2)

/home/hemantakumar.phurailatpam/bilby/0PN/hphc2.py:95: RuntimeWarning: invalid value encountered in power
  x = np.power(((G*M*2*np.pi*f)/( C**3*(l - (l + n)*k/(1 + k)))),(2/3))


array([   0.        ,  160.04099909,  209.02894068,  234.62508312,
        227.558986  ,  178.65681648,   79.27137691,  -78.74922218,
       -303.1368937 , -601.27008048])

In [31]:
np.nan_to_num(np.power(((G*20.0*2*np.pi*150)/( C**3*(1 - (1 + 2)*0.89915198/(1 + 0.89915198)))),2/3))

/home/hemantakumar.phurailatpam/anaconda3/envs/bilby/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


0.0

In [5]:
fplus.htilde0()

(5.428550568318762e-24+1.3082105549113993e-22j)

In [6]:
ff=C**3/(G*20*np.pi*6**(3/2))
l = np.arange(1,11,1)
fplus.uniarray( (l-(l+2)*(0.89915198/(1+0.89915198))) ,ff,100)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.real(-1+1j)

-1.0

In [5]:
np.log10(10)

1.0

In [6]:
tt = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt/100000000000000000000

array([1e-20, 2.097152e-14, 1.0460353203e-10, 4.398046511104e-08,
       4.76837158203125e-06, 0.00021936950640377855, 0.00558545864083284,
       -0.09223372036854775, -0.012614753107449505, 0.038758200196842126],
      dtype=object)

In [26]:
np.array([10000000000000000000000])/1

array([1e+22], dtype=object)

In [6]:
np.sum(10)

10