In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import hphc11
import hphc5
import hphc10
import h0CpxSpx5
import h05CpxSpx5
import h1CpxSpx5
import time

C = 299792458.
G = 6.67408*1e-11
Mo = 1.989*1e30
Mpc = 3.086*1e22

In [4]:
x = []
l = np.array([1,2,3]).astype('float64')
x.append( l + 1)
x.append( l + 2)
x.append( l + 3)


x = np.array(x)

In [9]:
_2b3 = np.array([l,\
                     l,\
                         l])

In [10]:
_2b3

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [4]:
mass_1 = 23.5
mass_2 = 21.5
symmetric_mass_ratio = (mass_1*mass_2)/((mass_1+mass_2)**2)
maximum_f = (C**3)/( G*(mass_1+mass_2)*Mo*np.pi*6**(3/2) )
mass_diff = (mass_1-mass_2)*Mo

In [5]:
symmetric_mass_ratio

0.24950617283950619

In [2]:
#m1=23.5, m2=21.5
injection_parameters = dict(chirp_mass=19.564163812778446, mass_ratio=0.9148936170212766, \
                            eccentricity=0.1, luminosity_distance=200.0, theta_jn=0.4, \
                            psi=0.1, phase=1.2, geocent_time=1180002601.0, ra=45.0, dec=5.73)

In [3]:
arg_plus = {'iota_':0.4, 'beta_':0.1, 'D_':200.0 , 'm1_':23.5, 'm2_':21.5, 'f_':30., 'f0_':20.0, 'Fp_':1.0, 'Fc_':0.0, 'et0_':0.1, 'phic_':1.2, 'tc_':1180002601.0}
arg_plus2 = {'iota_':0.4, 'beta_':0.1, 'D_':200.0 , 'm1_':23.5, 'm2_':21.5, 'f_':30., 'f0_':20.0, 'et0_':0.1, 'phic_':1.2, 'tc_':1180002601.0}
arg_plus3 = {'iota_':0.4, 'beta_':0.1, 'D_':200.0 , \
                        'f_':30.0, 'f0_':20.0, 'et0_':0.1, 'phic_':1.2, \
                        'tc_':1180002601.0, 'M_':45.0*Mo, 'eta_':0.24950617283950619, \
                        'ff_':97.68922304308887, 'delta_':3.9780000000000004e+30}
fplus = hphc5.Fn(**arg_plus)
fplus2 = hphc11.Fn(**arg_plus3)
fplus3 = hphc10.Fn(**arg_plus3)

In [4]:
fplus3.htilde()

((-1.654185839942542+0.9819009057667786j),
 (-0.9805839347354474-1.649902381289535j))

In [3]:
fplus2.htilde()

((-1.654201513472899+0.9818437222595874j),
 (-0.9805269389859735-1.6499180025008304j))

In [22]:
t0 = time.time()
for i in range(1000000):
    (1-766.4737128241678**2)**(7/4)
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0567


In [21]:
t0 = time.time()
for i in range(1000000):
    np.power((1-766.4737128241678**2),7/4,dtype=np.complex)
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 2.8078


In [5]:
t0 = time.time()
fplus3.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0331


In [11]:
fplus1.eccn(1,-2)

NameError: name 'fplus1' is not defined

In [5]:
fplus2.xi_l0(1,-2)

(-0.05800799034431211+0.1004727865213135j)

In [12]:
(1-766.4737128241678**2)**(7/4)

(8815036911.772095-8815036911.772099j)

In [14]:
np.power( ((1-766.4737128241678**2)*1j),(7/4) )/(1j)**(7/4)

(8815036911.772104+8815036911.772108j)

In [6]:
np.power((1-0.4**2),7/4,dtype=np.complex)

(0.7370360838796302+0j)

In [5]:
(1-766.4737128241678**2)**(7/4)

(8815036911.772095-8815036911.772099j)

In [7]:
fplus.htilde()

(5.5342731782875834e-24-5.013560269811376e-25j)

In [9]:
for ii in range(10):
    xil = fplus2.psi_l(ii+1,-3)
    print(xil)

-174.2305008050212
-141.35520752921354
-136.0392938134141
-157.71391805383195
-213.6917374899976
-312.35550884416284
-461.9902029791834
-670.5616693215887
-945.6972131545898
-1294.712198305867


In [33]:
for ii in range(10):
    et = fplus2.eccn(ii+1,-3)
    fn = h05CpxSpx5.Fn(et,sp.pi/3,sp.pi/3)
    Cp0 = fn.splus(ii+1,-3)
    print(Cp0, '  ',et)

0.0    0.014639220994070659
0.0    0.015169740956777217
0.0    0.015857117600498096
0.0    0.01636531750028254
0.0    0.016727243794910494
0.0    0.01699176458286298
0.0    0.017191620454341295
0.0    0.017347252350343536
0.0    0.01747160429999319
0.0    0.017573132516361795


In [32]:
ee = 0.01636531750028254
iota = np.pi/3
beta = np.pi/3
ee**3*( - 38*np.sin(iota)*np.sin(3*beta) - 38*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**(8*np.sin(iota)*np.sin(3*beta) + 8*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**5*(176/3*np.sin(iota)*np.sin(3*beta) + 176/3*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))

0.9999999999999957

In [34]:
ee = 0.01636531750028254
iota = np.pi/3
beta = np.pi/3
ee**3*( - 38*np.sin(iota)*np.sin(3*beta) - 38*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee*(8*np.sin(iota)*np.sin(3*beta) + 8*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + ee**5*(176/3*np.sin(iota)*np.sin(3*beta) + 176/3*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))

1.7334579170191625e-17

In [4]:
import time
t0 = time.time()
fplus.htilde()
#fplus2.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0406


In [5]:
import time
t0 = time.time()
print(fplus.htilde())
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

(-9.563236707058214e-24+7.965974785544314e-26j)
Execution took 5.4276


In [7]:
import time
t0 = time.time()
et = fplus.eccn(1,2)
fn = h05CpxSpx4.Fn(et,sp.pi/3,sp.pi/3)
fn.cplus(1,2)
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0179


In [16]:
for i in range(10):
    j=i+1
    et = fplus.eccn(j,2)
    fn = h1CpxSpx4.Fn(et,sp.pi/3,sp.pi/3,0.25)
    print(fn.scross(j,2),',',et)

2.430113800922941e-07 , 0.0055170314788476876
1.5546428121964128e-08 , 0.010164039876179361
1.0488859715430617e-09 , 0.01441331376393247
3.0807129028019986e-11 , 0.01572215720769032
0.0 , 0.016379140319968857
0.0 , 0.016779961721317377
0.0 , 0.017052124477030414
0.0 , 0.01724994913866151
0.0 , 0.01740070874052484
0.0 , 0.01751967950472511


In [9]:
mm=np.array([1,2,3])

In [12]:
float(1j+1)

TypeError: can't convert complex to float

In [15]:
import time
t0 = time.time()
fplus.htilde()
t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 5.1655


In [7]:
iota = np.pi/3
beta = np.pi/3
e = 0.014639220994070659
e**4 * ( - (65/192)*np.sin(iota)*np.sin(3*beta) - 65/192*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta)) + e**6 * ( - ((19*np.sin(iota)*np.sin(3*beta))/12288) - (19*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))/12288) + e**2 * (19/32*np.sin(iota)*np.sin(3*beta) + 19/32*np.cos(iota)**2*np.sin(iota)*np.sin(3*beta))

1.6867005329740134e-20

In [23]:
np.sin(np.pi-4e-22)

1.2246467991473532e-16

In [19]:
np.sin(np.pi)

1.2246467991473532e-16

In [13]:
Fp = 1.0
Fc = 0.0
Gamma_l = np.zeros((10,3))
Sigma_l = np.zeros((10,3))
for i in range(10):
    for j in range(3):                                                                     
        Gamma_l[i,j] = Fp*fn.cplus(i,j) + Fc*fn.ccross(i,j)
        Sigma_l[i,j] = Fp*fn.splus(i,j) + Fc*fn.scross(i,j)

In [14]:
Gamma_l

array([[ 4.13775787e-03, -5.17213174e-03, -1.53058958e-08],
       [ 7.74781119e-05,  1.24967718e+00, -8.33819259e-10],
       [ 2.52612336e-06,  4.05174471e-02, -4.64708571e-11],
       [ 6.10889483e-08,  1.23516753e-03, -1.15372685e-12],
       [ 1.43901584e-09,  3.57337728e-05,  0.00000000e+00],
       [ 3.39025282e-11,  1.00256870e-06,  0.00000000e+00],
       [ 0.00000000e+00,  2.76076541e-08,  0.00000000e+00],
       [ 0.00000000e+00,  7.49418430e-10,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [15]:
Sigma_l

array([[ 0.00000000e+00,  8.95839495e-03, -2.65105892e-08],
       [ 0.00000000e+00, -2.16450437e+00, -1.44421732e-09],
       [ 0.00000000e+00, -7.01782769e-02, -8.04898857e-11],
       [ 0.00000000e+00, -2.13937292e-03, -1.99831352e-12],
       [ 0.00000000e+00, -6.18927101e-05,  0.00000000e+00],
       [ 0.00000000e+00, -1.73649993e-06,  0.00000000e+00],
       [ 0.00000000e+00, -4.78178595e-08,  0.00000000e+00],
       [ 0.00000000e+00, -1.29803080e-09,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])