In [1]:
import numpy as np
import matplotlib.pyplot as plt

import hphc2

C = 299792458.
G = 6.67408*1e-11
Mo = 1.989*1e30
Mpc = 3.086*1e22

In [2]:
arg_plus = {'iota_':np.pi/3, 'beta_':np.pi/3, 'D_':100. , 'm1_':10., 'm2_':10., 'f_':30., 'f0_':10., 'Fp_':1.0, 'Fc_':0.0, 'et0_':0.1, 'phic_':0., 'tc_':0.}
fplus = hphc2.Fn(**arg_plus)

In [3]:
fplus.psi_l(2)

array([ 1.31098912e+02,  1.64487929e+02,  1.42280706e+00, -4.32258160e+02,
       -1.20835278e+03, -2.39302688e+03, -4.04798957e+03, -6.23143656e+03,
       -8.99871649e+03, -1.24028103e+04])

In [4]:
fplus.htilde0()

(-3.4084254199762774e-23+4.2762435308873803e-23j)

In [16]:
fplus.psi_l(0).astype('float64')

array([    27.27201545,    -24.87383906,   -261.37074653,   -766.03128047,
        -1612.11644252,  -2866.25941284,  -4590.37048297,  -6842.74850747,
        -9678.80151179, -13151.54768533])

In [6]:
1+ \
\
2

3

In [5]:
np.log10(10)

1.0

In [6]:
tt = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt*tt/100000000000000000000

array([1e-20, 2.097152e-14, 1.0460353203e-10, 4.398046511104e-08,
       4.76837158203125e-06, 0.00021936950640377855, 0.00558545864083284,
       -0.09223372036854775, -0.012614753107449505, 0.038758200196842126],
      dtype=object)

In [26]:
np.array([10000000000000000000000])/1

array([1e+22], dtype=object)

In [6]:
np.sum(10)

10