In [1]:
import numpy as np

import hphc

/home/hemantakumar.phurailatpam/anaconda3/envs/bilby/lib/python3.7/site-packages/gwtools/rotations.py:63: UserWarning: Could not import GWFrames, needed for rotations module
  _warnings.warn("Could not import GWFrames, needed for rotations module")
/home/hemantakumar.phurailatpam/anaconda3/envs/bilby/lib/python3.7/site-packages/gwtools/__init__.py:11: UserWarning: Could not import rotations, decompositions, or fitfuncs. These are not needed by GWSurrogate.
  _warnings.warn("Could not import rotations, decompositions, or fitfuncs. These are not needed by GWSurrogate.")


setting __package__ to gwsurrogate.new so relative imports work
__name__ = gwsurrogate.new.spline_evaluation
__package__= gwsurrogate.new
setting __package__ to gwsurrogate.new so relative imports work
setting __package__ to gwsurrogate.new so relative imports work


In [2]:
hphc.Y(2,2,np.pi/3,np.pi/3)

(-0.1774077554545425+0.30727924610402235j)

In [2]:
hphc.Y(2,2,np.pi/3,np.pi/3)

(-0.1774077554545425+0.30727924610402235j)

In [4]:
aa = np.arange(-5,6,1)

In [5]:
aa

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [6]:
bb = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [8]:
bb[(aa<0)|abs(aa)>3] = 30

In [10]:
bb+1

array([31, 31,  3,  4,  5,  6,  7,  8,  9, 31, 31])

In [11]:
zz = bb[(aa<0)|abs(aa)>3]

In [12]:
zz

array([30, 30, 30, 30])

In [13]:
zz.sum()

120

In [14]:
import hphc2

In [18]:
import importlib
importlib.reload(hphc2)

<module 'hphc2' from '/home/hemantakumar.phurailatpam/bilby/com/hphc2.py'>

In [19]:
hphc2.Y(2,2,np.pi/3,np.pi/3)

(-0.1774077554545425+0.30727924610402235j)

In [26]:
import time 

t0 = time.time()
ff = hphc2.Y(2,2,np.pi/3,np.pi/3)

t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0006


In [27]:
import time 

t0 = time.time()
ff = hphc.Y(2,2,np.pi/3,np.pi/3)

t1 = time.time()
print('Execution took {:.4f}'.format(t1 - t0))

Execution took 0.0002
